project:
  type: book

book:
  title: "The {traits.build} data standard, R package, and workflow"
  author: ["Elizabeth Wenk", "Daniel Falster", "Sophie Yang", "Fonti Kar"]
  page-footer: "How to get help: <https://traitecoevo.github.io/traits.build-book/help.html><br>Copyright 2023, Daniel Falster and Elizabeth Wenk" 
  page-navigation: true
  chapters:
    - part: Introduction
      chapters:
        - index.qmd
        - motivation.qmd
        - workflow.qmd
        - usage_examples.qmd
    - part: Data structure and standard 
      chapters:
        - long_wide.qmd
        - database_standard.qmd
        - database_structure.qmd
        - database_metadata.qmd
        - dictionary.qmd
    - part: Creating with `traits.build`
      chapters:
        - traits_build.qmd
        - tutorial_compilation.qmd
        - file_organisation.qmd
        - create_dictionary.qmd
        - adding_data_brief.qmd
        - custom_R_code.qmd
        - publishing.qmd
    - part: "Guide to adding data"
      chapters:
        - adding_data_long.qmd
        - data_common_issues.qmd
        - tutorial_datasets.qmd
        - tutorial_dataset_1.qmd
        - tutorial_dataset_2.qmd
        - tutorial_dataset_3.qmd
        - tutorial_dataset_4.qmd
        - tutorial_dataset_5.qmd
        - tutorial_dataset_6.qmd
        - tutorial_dataset_7.qmd
    - part: Using outputs of `traits.build`
      chapters:
        - austraits_database.qmd
        - austraits_package.qmd
        - austraits_build_tutorial.qmd
    - part: Getting help
      chapters:
        - help.qmd
        - debugging.qmd

  appendices:
    - csv.qmd
    - yaml.qmd
  
format:
  html:
    theme: cosmo
    number-depth: 2
